import copy, sklearn, unitbuilder as ub, numpy as np

np.random.seed(0)
#THE AI TRAINS ON THE AVERAGE ORDER, SPLIT ACROSS ALL THE HISTORY
#THE AI IS SUPPLEMENTED WITH THE CONTEXT INJECTION, ALLOWING FOR INDIVIDUAL ORDERS TO BE RENDERED

num